### ISSUE TITLE
Convert s3.tf to aws@emory

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/avalon-terraform#14]
Change force_destroy from true to variable input. I would like to be able to preserve s3 buckets if desired.

Remove references to policy creation or attachement. aws@emory does not allow us to attach policies to users.
We will assume that the user is already created and has correct permissions, therefore the sections creating policy for s3 bucket access is not needed.

**Comment by lovinscari** [comment]
SH to look at this but believes the work is largely finished.
