### ISSUE TITLE
GIT  Sub-Tree Design

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon-terraform#16]
For Ann/Mark/Solomon:

- [x] Destroy arch in unrestricted account
- [x] Destroy test in unrestricted account
- [x] Destroy prod in unrestricted account

For Collin:

- [x] Delete unrestricted terraform repo
- [x] update lucidchart diagram

**Comment by libdgg** [comment]
[Link to the draft Git Repo Design diagram](https://lucid.app/lucidchart/1b5e09ad-0b58-4959-af93-2d0a3d5dc774/edit?page=hSVxfnUiiWza#?folder_id=home&browser=icon).

**Comment by libdgg** [comment]
NOTE: Wait until DNS setup for restricted and then we can destroy unrestricted environments.

**Comment by lovinscari** [comment]
Need to destroy the unrestricted account setup for Avalon which is ready to move as middleware has time. Also need to update the diagram and repository which CB will do.

**Comment by SolomonHD** [comment]
The unrestricted avalon workspaces/environments have all been deleted. Also I deleted the buckets for avalon, the ec2 keys and also the Github avalon-tf-ltds repo. All that's left is adjusting the diagram. Removing myself from ticket.

**Comment by libdgg** [comment]
@rotated8 updated this and went over it with @libdgg

**Comment by libdgg** [comment]
@rotated8 add this documentation to the wiki in general info.
wiki: https://wiki.emory.edu/pages/viewpage.action?pageId=172512552

**Comment by rotated8** [comment]
Linked to the repo diagram [here](https://wiki.emory.edu/display/ULTS/Avalon+General+Infomation)
