### ISSUE TITLE
Networking failure cannot reach anything in aws@emory account #247

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/avalon-terraform#17]

**Comment by lovinscari** [comment]
Paul Petersen's team has fixed this but there is another problem with certificate manager in AWS as we have reached our limit and cannot import any additional certs.

**Comment by SolomonHD** [comment]
The ACM cert limit has been increased to 2000 (from the base amount of 20). We shouldn't see the LimitExceeded Error again.
