### ISSUE TITLE
Unable to create content in application. 

### ISSUE THREAD

**Issue by libah** [emory-libraries/avalon-terraform#20]
The following is from the fedora log in Cloudwatch. It looks as though can't write to postgres. 

`org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "10.65.19.44", user "dbfcrepo", database "fcrepo", SSL off`

DB works for authentication, but not for Fedora. In cor-cm, Fedora also has SSL off, but that's for MySQL.

**Comment by rotated8** [comment]
The `SSL off` piece is worrisome to me. Seems like we may need to explicitly force Fedora into SSL?

Next step: CB will reach out to Phuong about how Fedora is built in the Docker

**Comment by rotated8** [comment]
Fedora is built via https://github.com/avalonmediasystem/avalon-docker/tree/aws_min in CodeBuild.

**Comment by libdgg** [comment]
Adding Solomon to this ticket. Solomon has reached out to Phuong today, waiting on response.

**Comment by SolomonHD** [comment]
I zoom'd with Phoung over this. Essentially `&useSSL=true` needs to be added to the end of [connectionUrl](https://github.com/fcrepo/fcrepo/blob/4.7-maintenance/fcrepo-configs/src/main/resources/config/jdbc-postgresql-s3/repository.jso)

This would involved forking [avalon-docker](https://github.com/avalonmediasystem/avalon-docker/tree/master/fedora) if we were to do it ourselves, the .war file needs to be edited. 

Phoung graciously offered to add this option in the avalon-docker repo. I assume this will be a conditional that will by default do nothing, and if a certain flag is present; add the useSSL option. He said he will do this by tomorrow.

To get this change on our servers we'll for sure have to edit the .env file, also do a docker pull.

**Comment by SolomonHD** [comment]
Worked with Phoung on this today; he created a fork that had ssl enabled for fedora. After editing the docker-compose.yml file on the ec2 to point to the Indiana fork for s3 fix, instead of Northwestern, and pulling the new images down, we got an error about SSL not being valid. Phoung found a workaround which skips the validation check on the client side. 

After that there was no longer an validation error in fedora but fedora itself is unavailable now for some unknown reason. We are still unable to create collections on the app.

Additionally, I sent a request to Paul Petersen and Zach Cox about allowing us to have a postgres server without SSL enabled.

**Comment by lovinscari** [comment]
Phoung made some updates on this issue yesterday and it was working briefly. @SolomonHD to update this ticket on changes that were made.

**Comment by SolomonHD** [comment]
Below are notes on the changes I had to make to get the fedora database working.

```
In docker compose file
switch fedora image from NU to IU
removed Modeshape from environemnt 
inside .env add new D flag: -Dfcrepo.modeshape.configuration=classpath:/config/jdbc-postgresql-s3/repository-ssl.json
Then rebuild and pull images on anything currently running.
If ssl not desired use: -Dfcrepo.modeshape.configuration=classpath:/config/jdbc-postgresql-s3/repository.json
```

I believe Phuong will make these changes in the [avalon-docker](https://github.com/avalonmediasystem/avalon-docker/blob/aws_ecs/docker-compose.yml) repo, then we would only have to select which modeshape -D flag to use, ssl or no ssl.

**Comment by AGCooper** [comment]
Waiting on the shib integration.

**Comment by libdgg** [comment]
NOTE: per the standup 11/19/2020 if we can add a video to the prod system we can close this ticket.

**Comment by libdgg** [comment]
NOTE: per standup 11/30/2020 content has been added to test (streaming issue exists being worked on with other tickets). we just need to add a video in prod to be able to confirm we can create content and upload a video and then we can close this ticket.
